site_name: 游离域/Yulliil Zone
site_url: https://blog.yulliil.moe
theme:
  name: material
  palette:
    primary: pink
    accent: pink
    palette:
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to system preference
    language: zh
    features:
      - search.suggest
      - search.highlight

plugins:
  - search:
      separator: '[\s\u200b\-]'
