site_name: 游离域/Yulliil Zone
site_description: 是 Yulliil 的博客呀
site_url: https://blog.yulliil.moe
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  custom_dir: overrides
  language: zh
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.footer
plugins:
  - search:
      separator: '[\s\u200b\-]'
  - blog:
      enabled: true
      blog_dir: .
      post_readtime: true
      post_readtime_words_per_minute: 300
  - tags
  - meta
  - rss:
      match_path: "posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      abstract_delimiter: ""
      abstract_chars_count: -1
      use_material_blog: true
      json_feed_enabled: false
      feeds_filenames:
        rss_created: rss.xml
        rss_updated: rss-updated.xml
nav:
  - 首页: index.md
  - 怪东西: posts/odd.md
  - 关于: posts/about.md

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  alternate:
    - name: 中文
      link: /zh/
      lang: zh
    - name: English
      link: /en/
      lang: en
